# Generated by Django 6.0.1 on 2026-01-17 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='joined_on',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='reporting_manager',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='slack_user_id',
            field=models.CharField(blank=True, help_text='Slack user ID (e.g. U01ABCDEF)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
