# Generated by Django 6.0.1 on 2026-01-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='slack_user_id',
            field=models.CharField(blank=True, help_text='Slack User ID (e.g. U06ABC123)', max_length=50, null=True),
        ),
    ]
