# Generated by Django 6.0.1 on 2026-01-13 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_alter_checkinassignment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinassignment',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='checkinassignment',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
