# Generated by Django 6.0.1 on 2026-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0005_alter_checkinassignment_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinform',
            name='all_submitted_notified',
            field=models.BooleanField(default=False),
        ),
    ]
