# Generated by Django 6.0.1 on 2026-01-19 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0006_checkinform_all_submitted_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinform',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 19, 9, 27, 28, 557099, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkinform',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2026, 1, 19, 9, 27, 41, 925487, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
