# Generated by Django 6.0.1 on 2026-01-19 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0007_checkinform_end_date_checkinform_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinform',
            name='all_submitted_notified',
        ),
        migrations.RemoveField(
            model_name='checkinform',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='checkinform',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='checkinform',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkinform',
            name='period',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20),
        ),
    ]
