# Generated by Django 6.0.1 on 2026-01-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0008_remove_checkinform_all_submitted_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinassignment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkinassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'Partially Filled'), ('SUBMITTED', 'Submitted')], default='PENDING', max_length=20),
        ),
    ]
