# Generated by Django 6.0.1 on 2026-01-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0011_alter_checkinassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Filled'), ('SUBMITTED', 'Submitted')], default='PENDING', max_length=20),
        ),
    ]
