# Generated by Django 6.0.1 on 2026-01-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0012_alter_checkinassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinform',
            name='admin_notified_on_complete',
            field=models.BooleanField(default=False),
        ),
    ]
