# Generated by Django 6.0.1 on 2026-01-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0013_checkinform_admin_notified_on_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkinassignment',
            name='checkin_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='checkins.checkinform'),
        ),
    ]
