# Generated by Django 6.0.1 on 2026-01-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0014_question_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinassignment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
