# Generated by Django 6.0.1 on 2026-01-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0015_checkinassignment_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinassignment',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
