# Generated by Django 6.0.1 on 2026-01-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0016_checkinassignment_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinassignment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
