# Generated by Django 6.0.1 on 2026-04-24 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0017_checkinassignment_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(choices=[('NEGATIVE', '😞 Negative'), ('NEUTRAL', '😐 Neutral'), ('POSITIVE', '😊 Positive')], default='NEUTRAL', max_length=20)),
                ('has_blocker', models.BooleanField(default=False)),
                ('blocker_types', models.JSONField(default=list)),
                ('blocker_text', models.TextField(blank=True)),
                ('energy_level', models.IntegerField(default=5)),
                ('ai_summary', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('checkin_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='checkins.checkinanswer')),
            ],
            options={
                'verbose_name': 'Check-in Analysis',
                'verbose_name_plural': 'Check-in Analyses',
            },
        ),
    ]
